import 'dart:async';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_comics/flutter_comics.dart';
import 'package:image/image.dart' as img;

import '../../ai/balloon_ai_client.dart';
import '../../bridge/models_mapping.dart';
import '../../i18n/language_registry.dart';
import '../../io/tile_writer.dart';
import '../controller.dart';
import '../theme.dart';
import 'common.dart';

/// vdd-comics-editor-uiux-lettering, Task 4.2: the reusable balloon editor
/// component (`02-visual.md`'s "Component: Balloon editor card") -- shared
/// between Lettering mode (Phase 5) and Edit mode's Properties panel
/// (Task 4.3). Owns language-tab selection, text editing, and the AI
/// generation flow end to end (routing/progress/success/failure), mutating
/// through [controller] directly the same way every other widget in this
/// app does -- no extra indirection layer.
///
/// Simplification vs. Specifications: text edits call
/// [EditorController.setLayerTranslation] immediately on every keystroke,
/// not debounced -- matches how every other live-editable field in this app
/// works (e.g. `NumberField`), and debouncing is a perf/RPC-volume
/// optimization with no correctness difference now that there's no RPC per
/// edit (Phase 2 correction: local mutation + one `saveComics` on demand).
class BalloonEditorCard extends StatefulWidget {
  const BalloonEditorCard({
    super.key,
    required this.controller,
    required this.layer,
    required this.registry,
    required this.aiClient,
  });

  final EditorController controller;
  final EditorLayer layer;
  final LanguageRegistry registry;
  final BalloonAiClient aiClient;

  @override
  State<BalloonEditorCard> createState() => _BalloonEditorCardState();
}

enum _Phase { idle, generating, success, failure }

class _BalloonEditorCardState extends State<BalloonEditorCard> {
  String? _selectedLangCode;
  late TextEditingController _textController;
  StreamSubscription<GenerationEvent>? _sub;
  _Phase _phase = _Phase.idle;
  RoutingDecided? _routing;
  Failure? _failure;
  Uint8List? _freshPreview; // just-generated bytes, before the next stitch-from-disk
  Uint8List? _stitchedPreview;
  bool _previewIsFallback = false;
  int _previewRequestId = 0;

  /// vdd-comics-editor-uiux-lettering, Task 7.3: the translation text at the
  /// moment the *current* success result was generated -- set on a
  /// successful generation, cleared whenever `_phase` leaves `success`
  /// (language switch, layer switch). While non-null, a live mismatch
  /// against the current text means the artwork on screen no longer matches
  /// what the user has typed -- the Specifications edge case this task
  /// exists to surface, since nothing here auto-regenerates on text edits.
  String? _generatedFromText;

  static final Uint8List _blankPlaceholderPng =
      Uint8List.fromList(img.encodePng(img.Image(width: 1, height: 1)));

  @override
  void initState() {
    super.initState();
    _selectedLangCode = _defaultLangCode();
    _textController = TextEditingController(text: _currentText());
    _loadPreview();
  }

  @override
  void didUpdateWidget(covariant BalloonEditorCard oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.layer != widget.layer) {
      _resetForNewLayer();
    }
  }

  @override
  void dispose() {
    _sub?.cancel();
    _textController.dispose();
    super.dispose();
  }

  void _resetForNewLayer() {
    _sub?.cancel();
    _sub = null;
    _phase = _Phase.idle;
    _routing = null;
    _failure = null;
    _freshPreview = null;
    _generatedFromText = null;
    _selectedLangCode = _defaultLangCode();
    _textController.text = _currentText();
    _loadPreview();
  }

  String? _defaultLangCode() =>
      widget.layer.translations.isEmpty ? null : widget.layer.translations.keys.first;

  String _currentText() =>
      _selectedLangCode == null ? '' : widget.layer.translations[_selectedLangCode] ?? '';

  bool get _isHandLettered => widget.layer.style == 'hand_lettered';

  /// Languages this balloon already has text and/or artwork for -- the tab
  /// row shows these plus `[+ Add]` for anything else in the registry.
  List<String> _usedLanguages() {
    final used = <String>{...widget.layer.translations.keys};
    for (var i = 0; i < widget.layer.images.length; i++) {
      // Same real-tile-template guard as _hasArtwork -- a freshly-constructed
      // EditorLayer's synthetic placeholder filename shouldn't count as "used".
      if (widget.layer.images[i].file.contains('{0}')) {
        final code = widget.registry.codeFor(i);
        if (code != null) used.add(code);
      }
    }
    final order = {for (var i = 0; i < widget.registry.languages.length; i++)
      widget.registry.languages[i].code: i};
    final list = used.toList()
      ..sort((a, b) => (order[a] ?? 1 << 30).compareTo(order[b] ?? 1 << 30));
    return list;
  }

  bool _hasArtwork(String langCode) {
    final index = widget.registry.indexFor(langCode);
    if (index == null || index >= widget.layer.images.length) return false;
    final file = widget.layer.images[index].file;
    // A freshly-constructed EditorLayer seeds images[0].file with its own
    // `name` as a placeholder swatch convention (see EditorLayer's
    // constructor) -- that's not real tiled artwork, so require an actual
    // tile template here, matching stitchImage's own guard.
    return file.isNotEmpty && file.contains('{0}');
  }

  Future<Uint8List?> _stitchFor(String langCode) async {
    final document = widget.controller.coreDoc;
    final tempFolder = document?.tempFolder;
    if (tempFolder == null) return null;
    final index = widget.registry.indexFor(langCode);
    if (index == null || index >= widget.layer.images.length) return null;
    final image = widget.layer.images[index];
    if (image.file.isEmpty) return null;
    final layerIndex = widget.controller.doc!.layers.indexOf(widget.layer);
    final dims = imageDimensions(document!, layerIndex, index);
    if (dims == null) return null;
    return stitchImage(
      layersDir: '$tempFolder/layers',
      fileTemplate: image.file,
      width: dims.width,
      height: dims.height,
    );
  }

  Future<void> _loadPreview() async {
    final requestId = ++_previewRequestId;
    final langCode = _selectedLangCode;
    Uint8List? bytes;
    var isFallback = false;
    if (langCode != null) {
      bytes = await _stitchFor(langCode);
      if (bytes == null) {
        // "No artwork yet for Uk -- preview shows En as fallback" (02-visual.md).
        final fallbackCode = widget.registry.codeFor(0);
        if (fallbackCode != null && fallbackCode != langCode) {
          bytes = await _stitchFor(fallbackCode);
          isFallback = bytes != null;
        }
      }
    }
    if (!mounted || requestId != _previewRequestId) return;
    setState(() {
      _stitchedPreview = bytes;
      _previewIsFallback = isFallback;
    });
  }

  void _selectLanguage(String? langCode) {
    setState(() {
      _selectedLangCode = langCode;
      _textController.text = _currentText();
      _phase = _Phase.idle;
      _failure = null;
      _freshPreview = null;
      _generatedFromText = null;
    });
    _loadPreview();
  }

  void _onTextChanged(String text) {
    final langCode = _selectedLangCode;
    if (langCode == null) return;
    widget.controller.setLayerTranslation(langCode, text);
    setState(() {}); // language tab fill-state depends on translations
  }

  Future<void> _pickAddLanguage(BuildContext context) async {
    final used = _usedLanguages().toSet();
    final available = [
      for (final lang in widget.registry.languages)
        if (!used.contains(lang.code)) lang,
    ];
    if (available.isEmpty) return;
    final picked = await showMenu<String>(
      context: context,
      position: const RelativeRect.fromLTRB(100, 100, 0, 0),
      items: [
        for (final lang in available)
          PopupMenuItem(value: lang.code, child: Text('${lang.name} (${lang.code})')),
      ],
    );
    if (picked != null) _selectLanguage(picked);
  }

  /// The button is enabled whenever there's text (per `02-visual.md`'s
  /// "text entered, not yet generated" state, which shows Generate enabled
  /// even when the preview is still showing a fallback/placeholder) -- the
  /// actual source image is resolved lazily in [_generate] itself, awaited
  /// directly rather than depending on [_loadPreview]'s fire-and-forget
  /// background load having already finished.
  Future<Uint8List> _resolveSourceBytes(String langCode) async {
    if (_freshPreview != null) return _freshPreview!;
    if (_stitchedPreview != null) return _stitchedPreview!;
    final own = await _stitchFor(langCode);
    if (own != null) return own;
    final fallbackCode = widget.registry.codeFor(0);
    if (fallbackCode != null && fallbackCode != langCode) {
      final fallback = await _stitchFor(fallbackCode);
      if (fallback != null) return fallback;
    }
    // No artwork anywhere for this balloon yet -- a minimal blank
    // placeholder so BalloonAiClient.generate's required sourceBalloonPng
    // still has something real to work from (Specifications: the contract
    // requires bytes; this flow doesn't otherwise define a "generate from
    // nothing" case).
    return _blankPlaceholderPng;
  }

  Future<void> _generate() async {
    final langCode = _selectedLangCode;
    if (langCode == null || _isHandLettered) return;

    // Shows the generating state immediately on tap, before resolving the
    // source image -- both for responsiveness and so the state transition
    // doesn't depend on how long the (possibly real-disk-I/O-backed) source
    // resolution takes.
    setState(() {
      _phase = _Phase.generating;
      _routing = null;
      _failure = null;
    });

    final source = await _resolveSourceBytes(langCode);
    if (!mounted) return;

    final stream = widget.aiClient.generate(
      sourceBalloonPng: source,
      targetText: widget.layer.translations[langCode] ?? '',
      targetLangCode: langCode,
      isHandLettered: _isHandLettered,
    );

    _sub = stream.listen((event) {
      if (!mounted) return;
      switch (event) {
        case RoutingDecided():
          setState(() => _routing = event);
        case Progress():
          break; // stage text not modeled separately -- routing message covers it
        case Success():
          _onGenerationSuccess(langCode, event);
        case Failure():
          setState(() {
            _phase = _Phase.failure;
            _failure = event;
          });
      }
    });
  }

  Future<void> _onGenerationSuccess(String langCode, Success event) async {
    await widget.controller.setImageFile(langCode, event.pngBytes);
    if (!mounted) return;
    setState(() {
      _phase = _Phase.success;
      _freshPreview = event.pngBytes;
      _generatedFromText = widget.layer.translations[langCode] ?? '';
    });
  }

  void _cancelGeneration() {
    _sub?.cancel();
    _sub = null;
    setState(() {
      _phase = _Phase.idle;
      _routing = null;
    });
  }

  void _retry() => _generate();

  void _editText() {
    setState(() {
      _phase = _Phase.idle;
      _failure = null;
    });
  }

  static String _styleLabel(String? style) => switch (style) {
        'hand_lettered' => 'hand-lettered',
        'caption' => 'caption',
        _ => 'speech',
      };

  static Color _styleColor(String? style) => switch (style) {
        'hand_lettered' => Hs.coral500,
        'caption' => Hs.amber500,
        _ => Hs.violet500,
      };

  static String _failureMessage(String reason) => switch (reason) {
        'text_overflow' => "Text didn't fit the balloon even at minimum size.",
        'render_error' => "Couldn't render this text with the current font/shaping engine.",
        'network_required' =>
          "This device can't generate this language offline, and there's no network connection.",
        'hand_lettered' => 'This balloon is hand-lettered and cannot be AI-generated.',
        _ => 'Something went wrong generating this artwork.',
      };

  @override
  Widget build(BuildContext context) {
    final l = widget.layer;
    final styleColor = _styleColor(l.style);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _CardHeader(name: l.name, styleLabel: _styleLabel(l.style), styleColor: styleColor),
        const SizedBox(height: 10),
        _ArtworkPreview(
          bytes: _freshPreview ?? _stitchedPreview,
          isFallback: _freshPreview == null && _previewIsFallback,
          fallbackLangCode: widget.registry.codeFor(0),
          hasAnyText: l.translations.isNotEmpty,
        ),
        const SizedBox(height: 14),
        if (_isHandLettered)
          _HandLetteredNotice()
        else ...[
          _LanguageTabs(
            usedLanguages: _usedLanguages(),
            selected: _selectedLangCode,
            hasArtwork: _hasArtwork,
            hasText: (code) => l.translations.containsKey(code),
            onSelect: _selectLanguage,
            onAdd: () => _pickAddLanguage(context),
          ),
          const SizedBox(height: 12),
          if (_selectedLangCode != null) ...[
            Text('TEXT (${_selectedLangCode!.toUpperCase()})', style: kSectionLabel),
            const SizedBox(height: 6),
            TextField(
              controller: _textController,
              maxLines: 3,
              minLines: 2,
              style: serifValue(Hs.textBody),
              decoration: InputDecoration(
                isDense: true,
                contentPadding: const EdgeInsets.all(10),
                filled: true,
                fillColor: Hs.gray50,
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(Hs.rChip),
                    borderSide: const BorderSide(color: Hs.cloud200)),
              ),
              onChanged: _onTextChanged,
            ),
            const SizedBox(height: 12),
            _GenerationControls(
              phase: _phase,
              routing: _routing,
              failure: _failure,
              failureMessage: _failure == null ? '' : _failureMessage(_failure!.reason),
              // Task 7.3: text edited after this success no longer matches
              // what the on-screen artwork was actually generated from.
              isStale: _generatedFromText != null &&
                  _generatedFromText != (l.translations[_selectedLangCode] ?? ''),
              canGenerate: _textController.text.isNotEmpty,
              onGenerate: _generate,
              onCancel: _cancelGeneration,
              onRetry: _retry,
              onEditText: _editText,
            ),
          ] else
            const _NoLanguageSelectedHint(),
        ],
      ],
    );
  }
}

class _CardHeader extends StatelessWidget {
  const _CardHeader({required this.name, required this.styleLabel, required this.styleColor});
  final String name;
  final String styleLabel;
  final Color styleColor;

  @override
  Widget build(BuildContext context) {
    return Row(children: [
      Expanded(
        child: Text(name,
            style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w500),
            overflow: TextOverflow.ellipsis),
      ),
      Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
        decoration: BoxDecoration(
          color: styleColor.withValues(alpha: .14),
          borderRadius: BorderRadius.circular(Hs.rChip),
          border: Border.all(color: styleColor.withValues(alpha: .4)),
        ),
        child: Text(styleLabel,
            style: TextStyle(fontSize: 11, fontWeight: FontWeight.w600, color: styleColor)),
      ),
    ]);
  }
}

class _ArtworkPreview extends StatelessWidget {
  const _ArtworkPreview({
    required this.bytes,
    required this.isFallback,
    required this.fallbackLangCode,
    required this.hasAnyText,
  });
  final Uint8List? bytes;
  final bool isFallback;
  final String? fallbackLangCode;
  final bool hasAnyText;

  @override
  Widget build(BuildContext context) {
    return Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
      AspectRatio(
        aspectRatio: 16 / 9,
        child: Container(
          decoration: BoxDecoration(
            color: Hs.gray50,
            border: Border.all(color: Hs.cloud200),
            borderRadius: BorderRadius.circular(Hs.rCard),
          ),
          alignment: Alignment.center,
          clipBehavior: Clip.antiAlias,
          child: bytes != null
              ? Image.memory(bytes!, fit: BoxFit.contain)
              : Column(mainAxisSize: MainAxisSize.min, children: [
                  const Icon(Icons.chat_bubble_outline, size: 28, color: Hs.textTertiary),
                  const SizedBox(height: 6),
                  Text(hasAnyText ? 'No artwork yet' : 'no text yet',
                      style: const TextStyle(fontSize: 12, color: Hs.textTertiary)),
                ]),
        ),
      ),
      if (isFallback && fallbackLangCode != null) ...[
        const SizedBox(height: 6),
        Text('No artwork yet for this language — preview shows ${fallbackLangCode!.toUpperCase()} as fallback',
            style: const TextStyle(fontSize: 11, color: Hs.textTertiary)),
      ],
    ]);
  }
}

class _LanguageTabs extends StatelessWidget {
  const _LanguageTabs({
    required this.usedLanguages,
    required this.selected,
    required this.hasArtwork,
    required this.hasText,
    required this.onSelect,
    required this.onAdd,
  });
  final List<String> usedLanguages;
  final String? selected;
  final bool Function(String) hasArtwork;
  final bool Function(String) hasText;
  final ValueChanged<String?> onSelect;
  final VoidCallback onAdd;

  @override
  Widget build(BuildContext context) {
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      const Text('LANGUAGE', style: kSectionLabel),
      const SizedBox(height: 6),
      Wrap(spacing: 6, runSpacing: 6, children: [
        for (final code in usedLanguages)
          _LanguageTab(
            code: code,
            isSelected: code == selected,
            isFilled: hasArtwork(code),
            hasText: hasText(code),
            onTap: () => onSelect(code),
          ),
        InkWell(
          onTap: onAdd,
          borderRadius: BorderRadius.circular(Hs.rChip),
          child: Container(
            height: 32,
            padding: const EdgeInsets.symmetric(horizontal: 10),
            alignment: Alignment.center,
            decoration: BoxDecoration(
              border: Border.all(color: Hs.cloud200),
              borderRadius: BorderRadius.circular(Hs.rChip),
            ),
            child: const Text('+ Add',
                style: TextStyle(fontSize: 13, color: Hs.primary, fontWeight: FontWeight.w500)),
          ),
        ),
      ]),
    ]);
  }
}

class _LanguageTab extends StatelessWidget {
  const _LanguageTab({
    required this.code,
    required this.isSelected,
    required this.isFilled,
    required this.hasText,
    required this.onTap,
  });
  final String code;
  final bool isSelected;
  final bool isFilled; // has artwork -- filled tab per 02-visual.md
  final bool hasText;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(Hs.rChip),
      child: Container(
        height: 32,
        padding: const EdgeInsets.symmetric(horizontal: 10),
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: isFilled ? Hs.blue500 : (isSelected ? Hs.blue100 : Hs.white),
          border: Border.all(color: isFilled ? Hs.blue500 : Hs.cloud200),
          borderRadius: BorderRadius.circular(Hs.rChip),
        ),
        child: Text(code.toUpperCase(),
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w600,
              color: isFilled ? Hs.white : Hs.textBody,
            )),
      ),
    );
  }
}

class _NoLanguageSelectedHint extends StatelessWidget {
  const _NoLanguageSelectedHint();
  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(vertical: 10),
      child: Text('Add a language to start lettering this balloon.',
          style: TextStyle(fontSize: 13, color: Hs.textSecondary)),
    );
  }
}

class _HandLetteredNotice extends StatelessWidget {
  const _HandLetteredNotice();
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Hs.coral500.withValues(alpha: .08),
        borderRadius: BorderRadius.circular(Hs.rChip),
        border: Border.all(color: Hs.coral500.withValues(alpha: .3)),
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        const Row(children: [
          Icon(Icons.info_outline, size: 16, color: Hs.coral500),
          SizedBox(width: 6),
          Expanded(
            child: Text(
                'This balloon was hand-lettered by an artist. AI generation is disabled here — '
                'flagged for manual work instead.',
                style: TextStyle(fontSize: 13, color: Hs.textBody)),
          ),
        ]),
        const SizedBox(height: 10),
        // "Art mode" doesn't exist as a distinct mode in this app yet --
        // this stays a stub until that surface exists, same treatment as
        // the file-picker stubs pending Task 6.1.
        HsButton('Open in Art mode to edit manually', variant: HsVariant.secondary, onTap: () {}),
      ]),
    );
  }
}

class _GenerationControls extends StatelessWidget {
  const _GenerationControls({
    required this.phase,
    required this.routing,
    required this.failure,
    required this.failureMessage,
    required this.isStale,
    required this.canGenerate,
    required this.onGenerate,
    required this.onCancel,
    required this.onRetry,
    required this.onEditText,
  });
  final _Phase phase;
  final RoutingDecided? routing;
  final Failure? failure;
  final String failureMessage;
  final bool isStale;
  final bool canGenerate;
  final VoidCallback onGenerate;
  final VoidCallback onCancel;
  final VoidCallback onRetry;
  final VoidCallback onEditText;

  @override
  Widget build(BuildContext context) {
    switch (phase) {
      case _Phase.generating:
        final onDevice = routing?.onDevice ?? true;
        final reason = routing?.reason;
        return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(children: [
            const Expanded(
              child: LinearProgressIndicator(minHeight: 6, color: Hs.blue500, backgroundColor: Hs.cloud200),
            ),
            const SizedBox(width: 10),
            HsButton('Cancel', variant: HsVariant.cancel, height: 32, onTap: onCancel),
          ]),
          const SizedBox(height: 8),
          Text(
            onDevice ? 'On-device · erasing existing text' : 'Cloud · this may take a little longer',
            style: const TextStyle(fontSize: 12, color: Hs.textSecondary),
          ),
          if (!onDevice && reason != null) ...[
            const SizedBox(height: 4),
            Text(reason, style: const TextStyle(fontSize: 12, color: Hs.textTertiary)),
          ],
        ]);

      case _Phase.success:
        if (isStale) {
          // Task 7.3: text changed since this artwork was generated -- the
          // Specifications edge case (nothing auto-regenerates on edit).
          // Falls back to the same idle-style "Generate" row rather than
          // "Regenerate", since the existing artwork no longer reflects
          // what's in the text field.
          return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Row(children: [
              const Icon(Icons.info_outline, size: 16, color: Hs.amber500),
              const SizedBox(width: 6),
              const Expanded(
                child: Text('Artwork may be outdated — text has changed since generation',
                    style: TextStyle(fontSize: 12, color: Hs.textSecondary)),
              ),
            ]),
            const SizedBox(height: 8),
            HsButton('Generate artwork with AI', onTap: canGenerate ? onGenerate : null),
          ]);
        }
        return Row(children: [
          HsButton('Regenerate', variant: HsVariant.secondary, onTap: canGenerate ? onGenerate : null),
          const SizedBox(width: 10),
          const Text('Generated just now', style: TextStyle(fontSize: 12, color: Hs.textSecondary)),
        ]);

      case _Phase.failure:
        return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(children: [
            const Icon(Icons.error_outline, size: 16, color: Hs.coral500),
            const SizedBox(width: 6),
            Expanded(
                child: Text(failureMessage,
                    style: const TextStyle(fontSize: 13, color: Hs.textBody))),
          ]),
          const SizedBox(height: 10),
          Row(children: [
            HsButton('Retry', onTap: failure!.retryable ? onRetry : null),
            const SizedBox(width: 10),
            HsButton('Edit text', variant: HsVariant.secondary, onTap: onEditText),
          ]),
        ]);

      case _Phase.idle:
        return Row(children: [
          HsButton('Generate artwork with AI', onTap: canGenerate ? onGenerate : null),
          const SizedBox(width: 10),
          const Text('(o) On-device', style: TextStyle(fontSize: 12, color: Hs.textSecondary)),
        ]);
    }
  }
}
